bootstrap3-typeahead.js

newVal is set to undefined when I am trying to use tpyeahead in Bootstrap-tagsinput:
https://github.com/timschlechter/bootstrap-tagsinput
This will cause exception in this.displayText(newVal): can not access 'name' of undefined.

Add null check for newVal to avoid exception.

---

bootstrap3-typeahead.js

Prevent errors in displayText function if the item or item.name is undefined.

Fix for displayText undefined values

---

README.md

Using ssh url may produce  `Failed to execute "git ls-remote --tags --heads git@github.com:bassjobsen/Bootstrap-3-Typeahead.git", exit code of #128 Warning: Permanently added 'github.com,192.30.252.130' (RSA) to the list of known hosts. Permission denied (publickey). fatal: Could not read from remote repository.  Please make sure you have the correct access rights and the repository exists.

Fix bower setup instructions. Use git url instead of ssh.

---

bootstrap3-typeahead.js

Currently only able to modify the resulting rendered HTML based on the text returned from the displayText function. 
We have item as an object, containing meta-data about the item (like what type of search result it was). 
We need to modify the output HTML based on the meta data of the item (insert icons/images/differently styled text, etc.), which is unavailable when calling the highlighter method. 
This change allows the highlighter to have access to the item and do whatever it needs to based on the metadata, as well as the parsed display text.

Allow highlighter to modify HTML based on item properties

---

bootstrap3-typeahead.js

If source is a function, the second param is the "proccess" function. The source function doesn't return anything, so callign "proccess" with items = undefined provoke a error in $.grep (process function).
If someone wasn't using the callback parameter, and the source returns someting (that will be proccess), for legacy, it could be:
```javascript
if($.isFunction(this.source)) {
var source = this.source(this.query, $.proxy(this.process, this));
if (source !== undefined) {
//legacy
this.process(source);
}
}
else if (this.source) {
this.process(this.source);
}
```

Avoid twice proccess

---

bootstrap3-typeahead.js

By removing
```javascript
this.$element.focus();
```
The popup is hiden after move the mouse over an option
```javascript
mouseleave: function (e) {
this.mousedover = false;
if (!this.focused && this.shown) this.hide();
}
```

Fix bug focus (introduced in pull request #193)

---

bootstrap3-typeahead.js

Value check is missing in the `$.fn.typeahead` constructor, around line 471 :
```
if (typeof option == 'string') {
if (arg.length > 1) {
data[option].apply(data, Array.prototype.slice.call(arg ,1));
} else {
data[option]();
}
}
```
If `data[option]` for some reason is undefined, a nasty _Cannot read property 'apply' of undefined_ is raised. This happens when the typeahead is used along with bootstrap-tagsinput, perhaps elsewhere too. There should be looked into how bootstrap-tagsinput uses the typeahead as well, but the typeahead itself should really make a sanity check on `data[option] `before treating it as valid :
```
if (typeof option == 'string' && data[option]) {
if (arg.length > 1) {
data[option].apply(data, Array.prototype.slice.call(arg ,1));
} else {
data[option]();
}
}
```
See …

Check if data[option] is undefined

---

bootstrap3-typeahead.js

The keyup event does not fire for Chinese pinyin input method which requires an extra selection among word candidates after all require characters being typed in.

bugfix for Chinese input method on mobile devices

---

bootstrap3-typeahead.js

Prevent crash when "item" is an object with property "name", but "name" is an empty string.
The previous shorthand would return "item" when "item.name" was an empty string, resulting in an exception.

Prevent crash when "item.name" is an empty string.

---

bootstrap3-typeahead.js

Fixing it by adding "propertychange" to input listener

Fix IE7 Unrecognize Input Change (#222)

---

bootstrap3-typeahead.js

This fixes the issue of the *addItem* not showing up in the dropdownmenu, if the items array has a length greater then specified in the *items* option.
The change pushes the addItem into the resultset after the slice has occurred, preventing it from being excluded from the final items collection.
This issue was mentioned by @schmijos in Issue #201

Fixes addItem not showing when item length greater than items limit

---

bootstrap3-typeahead.js

As noted in
https://github.com/bassjobsen/Bootstrap-3-Typeahead/issues/107, when
`showHintOnFocus` is not `false` and a user tabs into an auto-select field,
the `keyUp` from the tab press causes the first item in the list to be
selected.
This is rarely what is wanted, so this commit changes the `keyup`
handler to ignore tabs when the list is shown and `showHintOnFocus` is
set.
Note that this does mean that pressing the tab key when
`showHintOnFocus` is set will never select the highlighted item if any, whereas
when `showHintOnFocus` is false it will.

Handle tabbing into a field with showHintOnFocus

---

bootstrap3-typeahead.js

The current versions does not work with the latest Bloodhound version 0.11.1.
Bloodhound (since 0.11) needs three arguments. Two of them are callback functions (sync and async) for local and remote data processing. 
see https://github.com/twitter/typeahead.js/blob/master/src/bloodhound/bloodhound.js#L132
This PR will fix #218 and certain other issues I guess.

[fix] bloodhound since v0.11 needs two callback methods

---

bootstrap3-typeahead.js

Adding 3 options to associate a link (thank to the href property) to each item :
- followLinkOnSelect: follow the item's link when item is selected
- itemLink : callback function that defines the href property (like displayText)
- afterEmptySelect: event triggered when the select method is called with a empty link
I try to implement the behavior of twitter's search autocomplete

Add options to use href for each items

---

bootstrap3-typeahead.js

Add setDefault function to let people can set default select of typeahead.
`$input.typeahead('select2', {id:1,name:"test"})`
`alert($input.typeahead("getActive").id`

Add setDefault function to set default select

---

bootstrap3-typeahead.js

In bootstrap 4 we no longer use an additional div around the dropdown-items.
For this I needed 2 changes.
1. Add the 'addBack' functionality so I can select the item element it self
2. I added a itemContentSelector. With this you can change the selector for getting the element in which you want to add the content. For backwards compatibility reasons I have set this to 'a' as default.
To get a Bootstrap 4 example I had to set the following:
{
menu: "<div class=\"typeahead dropdown-menu\" role=\"listbox\"></div>",
item: "<button class=\"dropdown-item\" type=\"button\" role=\"option\"></button>",
headerHtml: "<h6 class=\"dropdown-header\"></h6>",
headerDivider: "<div class=\"dropdown-divider\"></div>",
itemContentSelector: '.dropdown-item'
}

#285 Improve Bootstrap 4 support

---

README.md

With markdown html tag, the ***class="typeahead"*** will be misse,  which misleads beginners.

README usage fix

---

README.md

Using jQuery with data attributes is a common enough use case that it would be helpful to explicitly state the issue in the README. Since the behavior caused by the bug is puzzling to debug (one word attributes work, any attribute more than one word doesn't work), this change should save developers some time.

Mention issue with data attributes and jQuery

---

bootstrap3-typeahead.js

This option is useful to display a text (eg. brief description) when over the mouse on item.
This option is useful to display a text (eg. brief description) when over the mouse on item.
```
$input.typeahead({
[...]
itemLink: function (item) {
return item.href;
},
itemTitle: function (item) {
return item.title;
},
}
```

Added itemTitle function/option to set menu item title

---

package.json

Hi!
When I do `npm i https://github.com/bassjobsen/Bootstrap-3-Typeahead.git` I got error:
```
npm ERR! path /Users/user/projects/project/node_modules/bootstrap-3-typeahead/node_modules/grunt/lib/grunt.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/user/projects/project/node_modules/bootstrap-3-typeahead/node_modules/grunt/lib/grunt.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2018-01-21T13_40_31_554Z-debug.log
```
So, this PR is a fix for that.

fix file not found issue
